2015-08-19 20:03:41,339 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-19 20:03:41,339 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-19 20:03:42,357 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-19 20:03:42,357 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-19 20:03:42,357 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-19 20:03:42,357 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-19 20:09:42,626 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-19 20:09:42,626 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-19 20:09:43,717 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-19 20:09:43,717 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-19 20:09:43,717 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-19 20:09:43,717 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 14:17:23,087 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:17:23,087 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:17:23,140 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/ea_services/views.py", line 466, in get
    if not da:
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: exploratory_analysis_dataset_access

2015-08-20 14:17:23,140 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/ea_services/views.py", line 466, in get
    if not da:
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: exploratory_analysis_dataset_access

2015-08-20 14:22:12,781 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:22:12,781 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:22:12,784 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/ea_services/views.py", line 453, in get
    if not da:
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: exploratory_analysis_dataset_access

2015-08-20 14:22:12,784 - exploratory_analysis - DEBUG - tb: Traceback (most recent call last):
  File "/usr/local/uvcdat/DiagnosticsViewer/django-app-1.8/ea/ea_services/views.py", line 453, in get
    if not da:
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/uvcdat/build/install/lib/python2.7/site-packages/Django-1.9.dev20150729190932-py2.7.egg/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: exploratory_analysis_dataset_access

2015-08-20 14:23:52,500 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 14:23:52,500 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:38:24,147 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:38:24,147 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:38:26,299 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:38:26,299 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:38:26,299 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:38:26,299 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:41:23,681 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:41:23,681 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:41:56,733 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:41:56,733 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:41:56,733 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:41:56,733 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:42:50,158 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:42:50,158 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:42:51,153 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:42:51,153 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:42:51,154 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:42:51,154 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:43:12,820 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:43:12,820 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:43:14,100 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:43:14,100 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:43:14,100 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:43:14,100 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:46:52,757 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:46:52,757 - exploratory_analysis - DEBUG - 
In Dataset_Access GET

2015-08-20 16:46:54,056 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:46:54,056 - exploratory_analysis - DEBUG - 
In Variables GET

2015-08-20 16:46:54,056 - exploratory_analysis - DEBUG - dataset_name: null
2015-08-20 16:46:54,056 - exploratory_analysis - DEBUG - dataset_name: null
